### ISSUE TITLE
Call to get phone info always failing

### ISSUE THREAD

**Issue by lowfreq2010** [Komche/phoneinformations#1]
Hello,

I copied enclosed emanple into new project and got the following error: 

`I/flutter (27979): Failed to get phone infos, error : PlatformException(error, length=0; index=3, null, java.lang.StringIndexOutOfBoundsException: length=0; index=3
I/flutter (27979): 	at java.lang.String.substring(String.java:2429)
I/flutter (27979): 	at com.komche.phoneinformations.PhoneinformationsPlugin.onMethodCall(PhoneinformationsPlugin.java:79)
I/flutter (27979): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter (27979): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (27979): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter (27979): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (27979): 	at android.os.Handler.handleCallback(Handler.java:942)
I/flutter (27979): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (27979): 	at android.os.Looper.loopOnce(Looper.java:211)
I/flutter (27979): 	at android.os.Looper.loop(Looper.java:300)
I/flutter (27979): 	at android.app.ActivityThread.main(ActivityThread.java:8225)
I/flutter (27979): 	at java.lang`

what do i do wrong? app asks for permissions when i run it and i answer yes to all permission requests

thanks in advance for ant help

**Comment by Komche** [comment]
Greetings,
The bug is fixed, it is triggered by devices that do not have a SIM card.
